language: php
php:
- "5.3"

before_script:
- git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
- rm -r ../cakephp/app/
- git clone git://github.com/christopherrolfe198/cakephp-timer ../cakephp/app
- chmod -R 777 ../cakephp/app/tmp
- mysql -e 'create database cakephp_test;'
- echo "<?php
  class DATABASE_CONFIG {
  public $test = array(
    'datasource' => 'Database/Mysql',
    'persistent' => false,
    'host' => '0.0.0.0',
    'login' => 'travis',
    'password' => '',
    'database' => 'cakephp_test',
    'prefix' => ''
    );
  }" > ../cakephp/app/Config/database.php

  script:
  - ./lib/Cake/Console/cake test app AllTests --stderr